version: '3.8'
services:
  jupyter:
    image: jupyter/base-notebook
    environment:
      JUPYTER_ENABLE_LAB: 'yes'
    ports:
      - 10000:8888
    volumes:
      - ./notebooks:/home/jovyan/notebooks
    restart: unless-stopped
networks:
  {}

